### PR TITLE
feat: add `.nvmrc` and package.json `engines` key

### LINKED ISSUE #68: 🛠 Tooling: `.nvmrc`
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/refined-saved-replies/issues?q=is%3Aissue+label%3A%22area%3A+tooling%22) and found none that matched my issue.

### Overview

Add an `.nvmrc` to enforce the correct Node version. Once added, a `nvm install` command could be ran from the repository root to use/install the correct version for the project.

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by Pinjasaur**
## PR Checklist

- [x] Addresses an existing open issue: fixes #68
- [x] That issue was marked as [accepting prs](https://github.com/JoshuaKGoldberg/refined-saved-replies/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/refined-saved-replies/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

Adds an `.nvmrc` with the latest Node LTS release plus an `engines` key in the `package.json` to specify the same version support. With this, an `nvm install` command may be ran from the repository root to use (and install, if necessary) the specified Node version for the project.

If you want this noted in e.g. the CONTRIBUTING.md or similar, let me know and I can update that accordingly. 🙂

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]
Perfect, thanks @Pinjasaur!

I like that the `.nvmrc` specifies an exact version, while `engines` is just the major version range.

**Comment by JoshuaKGoldberg** [comment]
> If you want this noted in e.g. the CONTRIBUTING.md or similar, let me know and I can update that accordingly. 🙂

Sure, that'd be great. Yes please! I'll merge this now to get it in, and if you want to send a PR I'm happy to ✅ that too.

**Comment by Pinjasaur** [comment]
@JoshuaKGoldberg do you want the same changes done for https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues/65?

**Comment by JoshuaKGoldberg** [comment]
Sure, if you have time & are up for it 😁 thanks!

**Pull request merged**
